### ISSUE TITLE
steps

### ISSUE THREAD

**Issue by jaimebayes** [egorhowell/Medium-Articles#3]
Hi, 

I am trying to run your markov_stationary.py code, but it throws this error:

**NameError: name 'steps' is not defined**

Maybe it is a list or array of consecutive numbers?

Thanks in advance,

**Comment by egorhowell** [comment]
Hello,

I am currently away on holiday, I will review it when I get home if that’s alright!

Egor

**Comment by egorhowell** [comment]
@jaimebayes Should be fixed now. You were right, it was just a list of consecutive number i.e. steps! The plot is meant to show how each coordinate changes with each step and eventually plateau as the Markov chain reaches the stationary distribution. Try running the code and let me know if it works now!

**Comment by jaimebayes** [comment]
Thanks, i appreciate your work,

Have a nice day
